### ISSUE TITLE
Allow file-less configuration

### ISSUE THREAD

**Issue by agneevX** [hurlenko/aria2-ariang-docker#14]
The ability to specify the aria2 config options via `command` would be very helpful.

```yml
services:
  aria2:
    image: hurlenko/aria2-ariang
    command:
      - --dir=/aria2/data
```

Since a shell script is already used, it is already possible to pass `$1` arguments onto the aria2 executable.
